<?php

/**
 * Created by PhpStorm.
 * User: islam
 * Date: 18/11/2016
 * Time: 18:13
 */
class Main
{
    public function run(){
        // echo "Привет, это просто проверка!";
        ob_start(); // output buffering function. To output dynamic functions as normal strings.
        require_once(URL::getPage());
        ob_get_flush(); // to return the value generated by the code as a normal string.
    }

}